"""The frozen research dossier: one manifest over every committed artifact.

``research/m2b/frozen_dossier.json`` (dossier schema version 3) supersedes
the additive provenance-v2 anchor as the single source of truth for the
dossier graph — there are never two competing graph files. It binds:

* the **discovery chain** — request plan, receipt, raw-bundle fingerprint,
  and the machine-verified discovery decision (JSON and rendered Markdown);
* the **primary acquisition chain** — request plan, receipt, raw-bundle
  fingerprint, acquisition evidence, and the selected attempt id;
* the **independent audit acquisition** — an explicit status object: either
  a full ``canonical_content_match`` record (plan/receipt/raw-bundle hashes
  plus the strict reacquisition-audit artifact) or an explicit
  ``not_performed`` reason. Never silently absent;
* the **dataset chain** — derived CSV SHA, canonical content fingerprint,
  manifest and quality-report byte anchors, and the dataset lock;
* **runtime and protocol** — the runtime contract, ``uv.lock``,
  ``pyproject.toml``, the protocol, and the protocol-registration commit;
* the **holdout and development evidence** — the committed holdout
  identity, the train/validation results and report, and the validation
  decision (JSON and Markdown).

:func:`verify_frozen_dossier` verifies graph *semantics*, not just hashes:
every artifact must hash to the manifest; every raw response must hash and
size to its receipt; receipts must agree with their plans; the raw
responses must semantically re-derive the derived OHLCV bytes; the derived
data must reproduce the canonical content fingerprint; the tracked
manifest/quality anchors must equal the regenerated bytes; the holdout
identity must recompute exactly from the verified dataset and protocol;
the train/validation results, report, and research decision must
regenerate byte-for-byte; the discovery decision must re-verify against
its raw response; the audit comparison must re-verify against the audit
raw when performed; and one package-version chain must hold throughout.
No check is silently optional in the production path.

All of this is hash-bound and tamper-evident within one repository. It is
**not** cryptographic authentication: there is no signing key and no
external attestation.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from eth_research import __version__
from eth_research._json import StrictJSONError, strict_json_loads
from eth_research.data.acquisition_plan import (
    AcquisitionAttemptReceipt,
    AcquisitionRequestPlan,
    load_acquisition_plan,
    load_acquisition_receipt,
    require_safe_json_filename,
)
from eth_research.data.builder import LoadedDataset, load_canonical_dataset
from eth_research.data.coinbase import AcquisitionEvidence, load_acquisition_evidence
from eth_research.data.lock import DatasetLock, load_dataset_lock, verify_dataset_lock
from eth_research.data.provenance import (
    DatasetManifest,
    content_fingerprint,
    require_hex64,
    require_int,
    require_nonempty_str,
    require_str,
    sha256_file,
)
from eth_research.data.validation import require_commit_sha, require_fingerprint
from eth_research.decision import (
    ResearchDecision,
    build_research_decision_from_results,
    render_research_decision,
)
from eth_research.discovery import (
    load_discovery_decision,
    render_discovery_decision,
    verify_discovery_decision_from_raw,
)
from eth_research.environment import load_runtime_contract
from eth_research.gitcheck import is_commit_object
from eth_research.holdout import HoldoutIdentity, build_holdout_identity
from eth_research.protocol import (
    BenchmarkProtocol,
    BenchmarkResults,
    SegmentMetrics,
    verify_protocol,
)

DOSSIER_SCHEMA_VERSION: int = 3
FROZEN_DOSSIER_RELPATH: str = "research/m2b/frozen_dossier.json"
REACQUISITION_AUDIT_RELPATH: str = "research/m2b/reacquisition_audit.json"

AUDIT_NOT_PERFORMED: str = "not_performed"
AUDIT_CANONICAL_CONTENT_MATCH: str = "canonical_content_match"
AUDIT_CONTENT_DISCREPANCY: str = "content_discrepancy"
_AUDIT_STATUSES: tuple[str, ...] = (
    AUDIT_NOT_PERFORMED,
    AUDIT_CANONICAL_CONTENT_MATCH,
    AUDIT_CONTENT_DISCREPANCY,
)

_DISCOVERY_ATTEMPT: str = "discovery-001"
_CANONICAL_ATTEMPT: str = "coinbase-eth-usd-001"

_AUDIT_KEYS: frozenset[str] = frozenset(
    {
        "status",
        "reason",
        "audit_attempt_id",
        "audit_request_plan_sha256",
        "audit_receipt_sha256",
        "audit_raw_bundle_fingerprint",
        "reacquisition_audit_sha256",
    }
)

_REACQ_KEYS: frozenset[str] = frozenset(
    {
        "reacquisition_schema_version",
        "original_attempt_id",
        "audit_attempt_id",
        "workflow_run_id",
        "source_commit",
        "original_request_plan_sha256",
        "audit_request_plan_sha256",
        "original_receipt_sha256",
        "audit_receipt_sha256",
        "original_raw_bundle_fingerprint",
        "audit_raw_bundle_fingerprint",
        "original_derived_csv_sha256",
        "audit_derived_csv_sha256",
        "original_content_fingerprint",
        "audit_content_fingerprint",
        "original_row_count",
        "audit_row_count",
        "original_first_open_time",
        "original_last_open_time",
        "audit_first_open_time",
        "audit_last_open_time",
        "comparison_status",
        "differing_candle_count",
        "canonical_data_replaced",
    }
)

_DOSSIER_KEYS: frozenset[str] = frozenset(
    {
        "dossier_schema_version",
        "package_version",
        "discovery_request_plan_sha256",
        "discovery_receipt_sha256",
        "discovery_raw_bundle_fingerprint",
        "discovery_decision_sha256",
        "discovery_decision_markdown_sha256",
        "selected_attempt_id",
        "acquisition_request_plan_sha256",
        "acquisition_receipt_sha256",
        "raw_bundle_fingerprint",
        "acquisition_evidence_sha256",
        "independent_audit",
        "derived_csv_sha256",
        "dataset_content_fingerprint",
        "dataset_manifest_sha256",
        "quality_report_sha256",
        "dataset_lock_sha256",
        "runtime_contract_sha256",
        "uv_lock_sha256",
        "pyproject_sha256",
        "protocol_sha256",
        "protocol_registration_commit_sha",
        "holdout_identity_sha256",
        "train_validation_results_sha256",
        "train_validation_report_sha256",
        "validation_decision_sha256",
        "validation_decision_markdown_sha256",
    }
)


class DossierError(RuntimeError):
    """The frozen dossier is invalid or an artifact disagrees with it."""


_RAW_BUNDLE_HEADER: bytes = b"eth-research raw-bundle-v1\n"
RAW_BUNDLE_AGGREGATE_CAP_BYTES: int = 10 * 1024 * 1024


def raw_bundle_fingerprint(receipt: AcquisitionAttemptReceipt, attempt_dir: str | Path) -> str:
    """Domain-separated fingerprint of the exact raw response files.

    Over canonical ordered ``ordinal|filename|byte_length|raw_sha256``
    records, re-checking every file's actual length and hash so a forged
    ``byte_length`` (or a swapped body) is caught. Ordinals must be exactly
    ``0..N-1``, filenames unique and safe, no symlinks, and the aggregate
    must stay under the raw cap.
    """
    directory = Path(attempt_dir)
    responses = sorted(receipt.responses, key=lambda response: response.ordinal)
    if [response.ordinal for response in responses] != list(range(len(responses))):
        raise DossierError("receipt ordinals must be contiguous 0..N-1")
    if len({response.filename for response in responses}) != len(responses):
        raise DossierError("receipt filenames must be unique")
    hasher = hashlib.sha256()
    hasher.update(_RAW_BUNDLE_HEADER)
    aggregate = 0
    for response in responses:
        require_safe_json_filename("raw filename", response.filename)
        path = directory / response.filename
        if path.is_symlink():
            raise DossierError(f"raw body {response.filename} must not be a symlink")
        if not path.is_file():
            raise DossierError(f"raw body {response.filename} is missing")
        actual_length = path.stat().st_size
        if actual_length != response.byte_length:
            raise DossierError(
                f"raw body {response.filename} length {actual_length} != receipt "
                f"byte_length {response.byte_length}"
            )
        actual_sha = sha256_file(path)
        if actual_sha != response.sha256:
            raise DossierError(f"raw body {response.filename} SHA-256 does not match the receipt")
        aggregate += actual_length
        if aggregate > RAW_BUNDLE_AGGREGATE_CAP_BYTES:
            raise DossierError("raw bundle exceeds the aggregate byte cap")
        hasher.update(
            f"{response.ordinal}|{response.filename}|{response.byte_length}|{response.sha256}\n".encode(
                "ascii"
            )
        )
    return "sha256:" + hasher.hexdigest()


@dataclass(frozen=True)
class IndependentAuditRecord:
    """Explicit status of the independent integrity reacquisition.

    Either a full ``canonical_content_match`` record binding the audit
    chain, or an explicit ``not_performed`` reason. A discrepancy status
    exists so a failed comparison can be recorded honestly; it never
    verifies as a healthy dossier.
    """

    status: str
    reason: str | None
    audit_attempt_id: str | None
    audit_request_plan_sha256: str | None
    audit_receipt_sha256: str | None
    audit_raw_bundle_fingerprint: str | None
    reacquisition_audit_sha256: str | None

    def __post_init__(self) -> None:
        status = require_str("independent_audit.status", self.status)
        if status not in _AUDIT_STATUSES:
            raise ValueError(
                f"independent_audit.status must be one of {_AUDIT_STATUSES}, got {status!r}"
            )
        if status == AUDIT_NOT_PERFORMED:
            require_nonempty_str("independent_audit.reason", self.reason)
            for label in (
                "audit_attempt_id",
                "audit_request_plan_sha256",
                "audit_receipt_sha256",
                "audit_raw_bundle_fingerprint",
                "reacquisition_audit_sha256",
            ):
                if getattr(self, label) is not None:
                    raise ValueError(f"independent_audit.{label} must be null when not performed")
        else:
            if self.reason is not None:
                raise ValueError("independent_audit.reason must be null when performed")
            require_nonempty_str("independent_audit.audit_attempt_id", self.audit_attempt_id)
            require_hex64(
                "independent_audit.audit_request_plan_sha256", self.audit_request_plan_sha256
            )
            require_hex64("independent_audit.audit_receipt_sha256", self.audit_receipt_sha256)
            require_fingerprint(
                "independent_audit.audit_raw_bundle_fingerprint",
                self.audit_raw_bundle_fingerprint,
            )
            require_hex64(
                "independent_audit.reacquisition_audit_sha256", self.reacquisition_audit_sha256
            )

    def to_json_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "reason": self.reason,
            "audit_attempt_id": self.audit_attempt_id,
            "audit_request_plan_sha256": self.audit_request_plan_sha256,
            "audit_receipt_sha256": self.audit_receipt_sha256,
            "audit_raw_bundle_fingerprint": self.audit_raw_bundle_fingerprint,
            "reacquisition_audit_sha256": self.reacquisition_audit_sha256,
        }

    @classmethod
    def from_json_dict(cls, payload: object) -> IndependentAuditRecord:
        if not isinstance(payload, dict):
            raise ValueError("independent_audit must be an object")
        keys = set(payload)
        if keys != _AUDIT_KEYS:
            unknown = sorted(keys - _AUDIT_KEYS)
            missing = sorted(_AUDIT_KEYS - keys)
            raise ValueError(
                f"independent_audit keys do not match schema: unknown={unknown}, missing={missing}"
            )
        return cls(**{key: payload[key] for key in _AUDIT_KEYS})


@dataclass(frozen=True)
class ReacquisitionAudit:
    """Strict comparison record for the independent integrity reacquisition.

    Raw response bytes may differ between acquisitions; the relevant
    equality is the canonical parsed OHLCV content. ``comparison_status``
    is an enum, never free text, and the record states explicitly that the
    canonical data was not replaced.
    """

    reacquisition_schema_version: int
    original_attempt_id: str
    audit_attempt_id: str
    workflow_run_id: str
    source_commit: str
    original_request_plan_sha256: str
    audit_request_plan_sha256: str
    original_receipt_sha256: str
    audit_receipt_sha256: str
    original_raw_bundle_fingerprint: str
    audit_raw_bundle_fingerprint: str
    original_derived_csv_sha256: str
    audit_derived_csv_sha256: str
    original_content_fingerprint: str
    audit_content_fingerprint: str
    original_row_count: int
    audit_row_count: int
    original_first_open_time: str
    original_last_open_time: str
    audit_first_open_time: str
    audit_last_open_time: str
    comparison_status: str
    differing_candle_count: int
    canonical_data_replaced: bool

    def __post_init__(self) -> None:
        version = require_int("reacquisition_schema_version", self.reacquisition_schema_version)
        if version != 1:
            raise ValueError(f"unsupported reacquisition schema version {version!r}")
        require_nonempty_str("original_attempt_id", self.original_attempt_id)
        require_nonempty_str("audit_attempt_id", self.audit_attempt_id)
        if self.original_attempt_id == self.audit_attempt_id:
            raise ValueError("the audit attempt must be distinct from the original")
        require_nonempty_str("workflow_run_id", self.workflow_run_id)
        require_commit_sha("source_commit", self.source_commit)
        for label in (
            "original_request_plan_sha256",
            "audit_request_plan_sha256",
            "original_receipt_sha256",
            "audit_receipt_sha256",
            "original_derived_csv_sha256",
            "audit_derived_csv_sha256",
        ):
            require_hex64(label, getattr(self, label))
        for label in (
            "original_raw_bundle_fingerprint",
            "audit_raw_bundle_fingerprint",
            "original_content_fingerprint",
            "audit_content_fingerprint",
        ):
            require_fingerprint(label, getattr(self, label))
        for label in (
            "original_first_open_time",
            "original_last_open_time",
            "audit_first_open_time",
            "audit_last_open_time",
        ):
            require_nonempty_str(label, getattr(self, label))
        if self.comparison_status not in (
            AUDIT_CANONICAL_CONTENT_MATCH,
            AUDIT_CONTENT_DISCREPANCY,
        ):
            raise ValueError(
                f"comparison_status must be a comparison enum value, got {self.comparison_status!r}"
            )
        count = require_int("differing_candle_count", self.differing_candle_count)
        if self.comparison_status == AUDIT_CANONICAL_CONTENT_MATCH:
            if count != 0:
                raise ValueError("a canonical_content_match must have zero differing candles")
            if self.original_content_fingerprint != self.audit_content_fingerprint:
                raise ValueError("a canonical_content_match requires equal content fingerprints")
            if self.original_derived_csv_sha256 != self.audit_derived_csv_sha256:
                raise ValueError("a canonical_content_match requires equal derived CSV bytes")
            if self.original_row_count != self.audit_row_count:
                raise ValueError("a canonical_content_match requires equal row counts")
        elif count < 1:
            raise ValueError("a content_discrepancy must count at least one differing candle")
        if self.original_request_plan_sha256 != self.audit_request_plan_sha256:
            raise ValueError("the audit must fulfil the unchanged canonical request plan")
        if not isinstance(self.canonical_data_replaced, bool):
            raise ValueError("canonical_data_replaced must be a boolean")
        if self.canonical_data_replaced:
            raise ValueError(
                "canonical_data_replaced must be false: the audit never replaces frozen data"
            )

    def to_json_bytes(self) -> bytes:
        payload = {key: getattr(self, key) for key in sorted(_REACQ_KEYS)}
        text = json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False, allow_nan=False)
        return (text + "\n").encode("utf-8")

    @classmethod
    def from_json_bytes(cls, raw: bytes) -> ReacquisitionAudit:
        try:
            payload: Any = strict_json_loads(raw)
        except StrictJSONError as exc:
            raise ValueError(f"reacquisition audit is not valid JSON: {exc}") from exc
        if not isinstance(payload, dict):
            raise ValueError("reacquisition audit JSON must be an object")
        keys = set(payload)
        if keys != _REACQ_KEYS:
            unknown = sorted(keys - _REACQ_KEYS)
            missing = sorted(_REACQ_KEYS - keys)
            raise ValueError(
                f"reacquisition audit keys do not match schema: "
                f"unknown={unknown}, missing={missing}"
            )
        return cls(**{key: payload[key] for key in _REACQ_KEYS})


@dataclass(frozen=True)
class FrozenResearchDossier:
    """Strict manifest binding every committed dossier artifact."""

    dossier_schema_version: int
    package_version: str
    discovery_request_plan_sha256: str
    discovery_receipt_sha256: str
    discovery_raw_bundle_fingerprint: str
    discovery_decision_sha256: str
    discovery_decision_markdown_sha256: str
    selected_attempt_id: str
    acquisition_request_plan_sha256: str
    acquisition_receipt_sha256: str
    raw_bundle_fingerprint: str
    acquisition_evidence_sha256: str
    independent_audit: IndependentAuditRecord
    derived_csv_sha256: str
    dataset_content_fingerprint: str
    dataset_manifest_sha256: str
    quality_report_sha256: str
    dataset_lock_sha256: str
    runtime_contract_sha256: str
    uv_lock_sha256: str
    pyproject_sha256: str
    protocol_sha256: str
    protocol_registration_commit_sha: str
    holdout_identity_sha256: str
    train_validation_results_sha256: str
    train_validation_report_sha256: str
    validation_decision_sha256: str
    validation_decision_markdown_sha256: str

    def __post_init__(self) -> None:
        version = require_int("dossier_schema_version", self.dossier_schema_version)
        if version != DOSSIER_SCHEMA_VERSION:
            raise ValueError(
                f"unsupported dossier schema version {version!r}; "
                f"this package reads version {DOSSIER_SCHEMA_VERSION}"
            )
        require_nonempty_str("package_version", self.package_version)
        require_nonempty_str("selected_attempt_id", self.selected_attempt_id)
        require_fingerprint("dataset_content_fingerprint", self.dataset_content_fingerprint)
        require_fingerprint("raw_bundle_fingerprint", self.raw_bundle_fingerprint)
        require_fingerprint(
            "discovery_raw_bundle_fingerprint", self.discovery_raw_bundle_fingerprint
        )
        require_commit_sha(
            "protocol_registration_commit_sha", self.protocol_registration_commit_sha
        )
        if not isinstance(self.independent_audit, IndependentAuditRecord):
            raise ValueError("independent_audit must be an IndependentAuditRecord")
        for label in (
            "discovery_request_plan_sha256",
            "discovery_receipt_sha256",
            "discovery_decision_sha256",
            "discovery_decision_markdown_sha256",
            "acquisition_request_plan_sha256",
            "acquisition_receipt_sha256",
            "acquisition_evidence_sha256",
            "derived_csv_sha256",
            "dataset_manifest_sha256",
            "quality_report_sha256",
            "dataset_lock_sha256",
            "runtime_contract_sha256",
            "uv_lock_sha256",
            "pyproject_sha256",
            "protocol_sha256",
            "holdout_identity_sha256",
            "train_validation_results_sha256",
            "train_validation_report_sha256",
            "validation_decision_sha256",
            "validation_decision_markdown_sha256",
        ):
            require_hex64(label, getattr(self, label))

    def to_json_bytes(self) -> bytes:
        payload = {key: getattr(self, key) for key in sorted(_DOSSIER_KEYS)}
        payload["independent_audit"] = self.independent_audit.to_json_dict()
        text = json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False, allow_nan=False)
        return (text + "\n").encode("utf-8")

    @classmethod
    def from_json_bytes(cls, raw: bytes) -> FrozenResearchDossier:
        try:
            payload: Any = strict_json_loads(raw)
        except StrictJSONError as exc:
            raise ValueError(f"frozen dossier is not valid JSON: {exc}") from exc
        if not isinstance(payload, dict):
            raise ValueError("frozen dossier JSON must be an object")
        keys = set(payload)
        if keys != _DOSSIER_KEYS:
            unknown = sorted(keys - _DOSSIER_KEYS)
            missing = sorted(_DOSSIER_KEYS - keys)
            raise ValueError(
                f"frozen dossier keys do not match schema: unknown={unknown}, missing={missing}"
            )
        fields = {key: payload[key] for key in _DOSSIER_KEYS - {"independent_audit"}}
        return cls(
            independent_audit=IndependentAuditRecord.from_json_dict(payload["independent_audit"]),
            **fields,
        )


def load_frozen_dossier(path: str | Path) -> FrozenResearchDossier:
    """Strictly parse a frozen-dossier file."""
    file = Path(path)
    try:
        return FrozenResearchDossier.from_json_bytes(file.read_bytes())
    except ValueError as exc:
        raise DossierError(f"invalid frozen dossier {file.name!r}: {exc}") from exc


def _attempt_dir(root: Path, attempt_id: str) -> Path:
    return root / "research" / "m2b" / "raw" / "coinbase" / attempt_id


def _default_audit_record(root: Path) -> IndependentAuditRecord:
    """The audit section derived from what is actually committed."""
    audit_file = root / REACQUISITION_AUDIT_RELPATH
    if not audit_file.is_file():
        return IndependentAuditRecord(
            status=AUDIT_NOT_PERFORMED,
            reason=(
                "independent reacquisition not yet performed; it requires the one-shot "
                "GitHub Actions audit workflow (direct container egress to Coinbase is "
                "denied)"
            ),
            audit_attempt_id=None,
            audit_request_plan_sha256=None,
            audit_receipt_sha256=None,
            audit_raw_bundle_fingerprint=None,
            reacquisition_audit_sha256=None,
        )
    audit = ReacquisitionAudit.from_json_bytes(audit_file.read_bytes())
    audit_receipt_path = _attempt_dir(root, audit.audit_attempt_id) / "acquisition_receipt.json"
    receipt = load_acquisition_receipt(audit_receipt_path)
    return IndependentAuditRecord(
        status=audit.comparison_status,
        reason=None,
        audit_attempt_id=audit.audit_attempt_id,
        audit_request_plan_sha256=audit.audit_request_plan_sha256,
        audit_receipt_sha256=sha256_file(audit_receipt_path),
        audit_raw_bundle_fingerprint=raw_bundle_fingerprint(
            receipt, _attempt_dir(root, audit.audit_attempt_id)
        ),
        reacquisition_audit_sha256=sha256_file(audit_file),
    )


def build_frozen_dossier(
    repo_root: str | Path, *, independent_audit: IndependentAuditRecord | None = None
) -> FrozenResearchDossier:
    """Compute the dossier manifest from the committed artifacts."""
    root = Path(repo_root)
    research = root / "research" / "m2b"
    discovery_receipt_path = _attempt_dir(root, _DISCOVERY_ATTEMPT) / "acquisition_receipt.json"
    discovery_receipt = load_acquisition_receipt(discovery_receipt_path)
    primary_receipt_path = _attempt_dir(root, _CANONICAL_ATTEMPT) / "acquisition_receipt.json"
    primary_receipt = load_acquisition_receipt(primary_receipt_path)
    manifest = DatasetManifest.from_json_bytes((research / "dataset_manifest.json").read_bytes())
    evidence = load_acquisition_evidence(research / "acquisition_evidence.json")

    from eth_research import m2b_report  # local import: m2b_report imports evaluation

    # Creation derives the registration commit from git history — the honest
    # source — never from a stored label that could have been relabelled.
    registration = m2b_report.protocol_commit_from_history(root)
    return FrozenResearchDossier(
        dossier_schema_version=DOSSIER_SCHEMA_VERSION,
        package_version=__version__,
        discovery_request_plan_sha256=sha256_file(research / "discovery_plan.json"),
        discovery_receipt_sha256=sha256_file(discovery_receipt_path),
        discovery_raw_bundle_fingerprint=raw_bundle_fingerprint(
            discovery_receipt, _attempt_dir(root, _DISCOVERY_ATTEMPT)
        ),
        discovery_decision_sha256=sha256_file(research / "discovery_decision.json"),
        discovery_decision_markdown_sha256=sha256_file(
            research / "EARLIEST_CONTINUOUS_DECISION.md"
        ),
        selected_attempt_id=primary_receipt.attempt_id,
        acquisition_request_plan_sha256=sha256_file(research / "acquisition_request_plan.json"),
        acquisition_receipt_sha256=sha256_file(primary_receipt_path),
        raw_bundle_fingerprint=raw_bundle_fingerprint(
            primary_receipt, _attempt_dir(root, _CANONICAL_ATTEMPT)
        ),
        acquisition_evidence_sha256=sha256_file(research / "acquisition_evidence.json"),
        independent_audit=(
            independent_audit if independent_audit is not None else _default_audit_record(root)
        ),
        derived_csv_sha256=evidence.derived_sha256,
        dataset_content_fingerprint=manifest.content_fingerprint,
        dataset_manifest_sha256=sha256_file(research / "dataset_manifest.json"),
        quality_report_sha256=sha256_file(research / "quality_report.json"),
        dataset_lock_sha256=sha256_file(research / "dataset_lock.json"),
        runtime_contract_sha256=sha256_file(research / "runtime_contract.json"),
        uv_lock_sha256=sha256_file(root / "uv.lock"),
        pyproject_sha256=sha256_file(root / "pyproject.toml"),
        protocol_sha256=sha256_file(research / "protocol.json"),
        protocol_registration_commit_sha=registration,
        holdout_identity_sha256=sha256_file(research / "holdout_identity.json"),
        train_validation_results_sha256=sha256_file(research / "train_validation_results.json"),
        train_validation_report_sha256=sha256_file(research / "train_validation_report.md"),
        validation_decision_sha256=sha256_file(research / "validation_decision.json"),
        validation_decision_markdown_sha256=sha256_file(research / "validation_decision.md"),
    )


@dataclass(frozen=True)
class DossierVerification:
    """Structured outcome of the complete dossier verification.

    Carries the verified models so the shared preparation path can reuse
    them without re-verifying — there is exactly one graph implementation.
    """

    ok: bool
    checks: tuple[str, ...]
    errors: tuple[str, ...]
    dossier: FrozenResearchDossier | None
    lock: DatasetLock | None
    protocol: BenchmarkProtocol | None
    dataset: LoadedDataset | None
    evidence: AcquisitionEvidence | None
    plan: AcquisitionRequestPlan | None
    receipt: AcquisitionAttemptReceipt | None
    holdout: HoldoutIdentity | None
    results: BenchmarkResults | None
    decision: ResearchDecision | None
    train_validation: tuple[SegmentMetrics, ...] | None
    protocol_registration_commit_sha: str | None

    def raise_for_status(self) -> None:
        if not self.ok:
            raise DossierError("frozen dossier verification failed: " + "; ".join(self.errors))


def verify_frozen_dossier(
    repo_root: str | Path,
    *,
    manifest_path: str | Path,
    raw_chunk_dir: str | Path,
    derived_csv: str | Path,
) -> DossierVerification:
    """Run the complete dossier graph and return a structured result.

    Stages run in dependency order; a failing stage records its error and
    stops (its dependents would be meaningless), so the result is never a
    partial success. ``ok`` is true only when every stage passed.
    """
    root = Path(repo_root)
    research = root / "research" / "m2b"
    checks: list[str] = []
    errors: list[str] = []
    state: dict[str, Any] = {}

    def check(name: str, condition: bool, detail: str) -> bool:
        checks.append(name)
        if not condition:
            errors.append(f"{name}: {detail}")
        return condition

    def result() -> DossierVerification:
        return DossierVerification(
            ok=not errors,
            checks=tuple(checks),
            errors=tuple(errors),
            dossier=state.get("dossier"),
            lock=state.get("lock"),
            protocol=state.get("protocol"),
            dataset=state.get("dataset"),
            evidence=state.get("evidence"),
            plan=state.get("plan"),
            receipt=state.get("receipt"),
            holdout=state.get("holdout"),
            results=state.get("results"),
            decision=state.get("decision"),
            train_validation=state.get("train_validation"),
            protocol_registration_commit_sha=state.get("registration"),
        )

    try:
        dossier = load_frozen_dossier(root / FROZEN_DOSSIER_RELPATH)
        state["dossier"] = dossier
        checks.append("dossier:parse")
    except (DossierError, OSError) as exc:
        errors.append(f"dossier:parse: {exc}")
        return result()

    # --- 1. Every artifact hashes to the manifest. -------------------------
    hashed = {
        "discovery_request_plan_sha256": research / "discovery_plan.json",
        "discovery_receipt_sha256": _attempt_dir(root, _DISCOVERY_ATTEMPT)
        / "acquisition_receipt.json",
        "discovery_decision_sha256": research / "discovery_decision.json",
        "discovery_decision_markdown_sha256": research / "EARLIEST_CONTINUOUS_DECISION.md",
        "acquisition_request_plan_sha256": research / "acquisition_request_plan.json",
        "acquisition_receipt_sha256": _attempt_dir(root, dossier.selected_attempt_id)
        / "acquisition_receipt.json",
        "acquisition_evidence_sha256": research / "acquisition_evidence.json",
        "dataset_manifest_sha256": research / "dataset_manifest.json",
        "quality_report_sha256": research / "quality_report.json",
        "dataset_lock_sha256": research / "dataset_lock.json",
        "runtime_contract_sha256": research / "runtime_contract.json",
        "uv_lock_sha256": root / "uv.lock",
        "pyproject_sha256": root / "pyproject.toml",
        "protocol_sha256": research / "protocol.json",
        "holdout_identity_sha256": research / "holdout_identity.json",
        "train_validation_results_sha256": research / "train_validation_results.json",
        "train_validation_report_sha256": research / "train_validation_report.md",
        "validation_decision_sha256": research / "validation_decision.json",
        "validation_decision_markdown_sha256": research / "validation_decision.md",
    }
    for field, path in hashed.items():
        try:
            ok = sha256_file(path) == getattr(dossier, field)
        except OSError:
            ok = False
        if not check(f"anchor:{field}", ok, f"artifact bytes changed or missing ({path.name})"):
            return result()

    # --- 2-4. Discovery + primary chains: receipts, plans, raw bundles. ----
    try:
        discovery_plan = load_acquisition_plan(research / "discovery_plan.json")
        discovery_receipt = load_acquisition_receipt(
            _attempt_dir(root, _DISCOVERY_ATTEMPT) / "acquisition_receipt.json"
        )
        plan = load_acquisition_plan(research / "acquisition_request_plan.json")
        receipt = load_acquisition_receipt(
            _attempt_dir(root, dossier.selected_attempt_id) / "acquisition_receipt.json"
        )
        state["plan"] = plan
        state["receipt"] = receipt
        checks.append("chains:parse")
    except Exception as exc:
        errors.append(f"chains:parse: {exc}")
        return result()
    if not check(
        "discovery:receipt_plan",
        discovery_receipt.plan_sha256 == discovery_plan.plan_sha256(),
        "discovery receipt cites a different plan",
    ):
        return result()
    try:
        discovery_bundle = raw_bundle_fingerprint(
            discovery_receipt, _attempt_dir(root, _DISCOVERY_ATTEMPT)
        )
        primary_bundle = raw_bundle_fingerprint(
            receipt, _attempt_dir(root, dossier.selected_attempt_id)
        )
        checks.append("raw_bundles:recompute")
    except Exception as exc:
        errors.append(f"raw_bundles:recompute: {exc}")
        return result()
    for name, ok, detail in (
        (
            "discovery:raw_bundle",
            discovery_bundle == dossier.discovery_raw_bundle_fingerprint,
            "discovery raw bundle fingerprint mismatch",
        ),
        (
            "primary:raw_bundle",
            primary_bundle == dossier.raw_bundle_fingerprint,
            "primary raw bundle fingerprint mismatch",
        ),
        (
            "primary:receipt_plan",
            receipt.plan_sha256 == plan.plan_sha256(),
            "primary receipt cites a different plan",
        ),
        (
            "primary:user_agent",
            receipt.user_agent == plan.user_agent,
            "receipt user-agent differs from the plan",
        ),
        (
            "primary:response_count",
            len(receipt.responses) == len(plan.windows),
            "receipt response count differs from the plan windows",
        ),
        (
            "primary:windows",
            all(
                any(
                    window.ordinal == response.ordinal and window.filename == response.filename
                    for window in plan.windows
                )
                for response in receipt.responses
            ),
            "a receipt response has no matching plan window",
        ),
        (
            "primary:attempt",
            receipt.attempt_id == dossier.selected_attempt_id,
            "receipt attempt id differs from the dossier",
        ),
    ):
        if not check(name, ok, detail):
            return result()

    # --- 5. Discovery decision re-verifies against its raw response. -------
    try:
        discovery_decision = load_discovery_decision(research / "discovery_decision.json")
        raw_bytes = (
            _attempt_dir(root, _DISCOVERY_ATTEMPT) / discovery_receipt.responses[0].filename
        ).read_bytes()
        verify_discovery_decision_from_raw(discovery_decision, raw_bytes)
        rendered = render_discovery_decision(discovery_decision)
        committed_md = (research / "EARLIEST_CONTINUOUS_DECISION.md").read_text(encoding="utf-8")
        if not check(
            "discovery:markdown",
            rendered == committed_md,
            "the committed discovery Markdown is not the rendering of the decision model",
        ):
            return result()
        checks.append("discovery:decision")
    except Exception as exc:
        errors.append(f"discovery:decision: {exc}")
        return result()

    # --- 6-8. Evidence, semantic re-derivation, dataset, protocol. ---------
    try:
        lock = load_dataset_lock(research / "dataset_lock.json")
        protocol = BenchmarkProtocol.from_json_bytes((research / "protocol.json").read_bytes())
        manifest, evidence = verify_dataset_lock(
            lock,
            manifest_path=manifest_path,
            acquisition_evidence_path=research / "acquisition_evidence.json",
            raw_chunk_dir=raw_chunk_dir,
            derived_csv=derived_csv,
        )
        state["lock"] = lock
        state["protocol"] = protocol
        state["evidence"] = evidence
        checks.append("dataset:lock_evidence_semantic")
    except Exception as exc:
        errors.append(f"dataset:lock_evidence_semantic: {exc}")
        return result()
    for name, ok, detail in (
        (
            "dataset:derived_sha",
            evidence.derived_sha256 == dossier.derived_csv_sha256
            and sha256_file(derived_csv) == dossier.derived_csv_sha256,
            "the derived CSV bytes are not the dossier's derived_csv_sha256",
        ),
        (
            "dataset:fingerprint_bindings",
            manifest.content_fingerprint
            == dossier.dataset_content_fingerprint
            == lock.content_fingerprint
            == protocol.dataset_content_fingerprint,
            "content fingerprint disagrees across manifest/lock/protocol/dossier",
        ),
        (
            "dataset:manifest_anchor",
            sha256_file(manifest_path) == dossier.dataset_manifest_sha256,
            "the regenerated manifest bytes differ from the tracked anchor",
        ),
    ):
        if not check(name, ok, detail):
            return result()
    try:
        dataset = load_canonical_dataset(manifest_path)
        if dataset.manifest != manifest:
            raise DossierError("the reloaded dataset's manifest is not the manifest the lock pins")
        verify_protocol(protocol, lock)
        if content_fingerprint(dataset.frame) != protocol.dataset_content_fingerprint:
            raise DossierError("the reloaded frame's recomputed fingerprint is not the protocol's")
        state["dataset"] = dataset
        checks.append("dataset:reload_fingerprint_protocol")
    except Exception as exc:
        errors.append(f"dataset:reload_fingerprint_protocol: {exc}")
        return result()

    # Quality anchor equals the regenerated quality report beside the manifest.
    quality_regen = Path(manifest_path).parent / dataset.manifest.quality_report_filename
    if not check(
        "dataset:quality_anchor",
        quality_regen.is_file()
        and quality_regen.read_bytes() == (research / "quality_report.json").read_bytes(),
        "the regenerated quality report differs from the tracked anchor",
    ):
        return result()

    # --- 9. Holdout identity recomputes exactly. ----------------------------
    try:
        holdout = build_holdout_identity(dataset, protocol)
        state["holdout"] = holdout
        checks.append("holdout:recompute")
    except Exception as exc:
        errors.append(f"holdout:recompute: {exc}")
        return result()
    if not check(
        "holdout:committed_bytes",
        holdout.to_json_bytes() == (research / "holdout_identity.json").read_bytes(),
        "the committed holdout identity does not recompute from the verified dataset",
    ):
        return result()

    # --- 10-12. Development evidence regenerates byte-for-byte. ------------
    from eth_research import evaluation, m2b_report  # local: they import this module

    try:
        # Strictly parses the committed results, so an edited number that
        # breaks the reconstructable accounting identities dies right here.
        registration = m2b_report.committed_protocol_registration_commit(root)
        checks.append("evidence:registration")
    except Exception as exc:
        errors.append(f"evidence:registration: {exc}")
        return result()
    if not check(
        "evidence:registration_dossier",
        registration == dossier.protocol_registration_commit_sha,
        "the results' registration commit differs from the dossier's",
    ):
        return result()
    if not check(
        "evidence:registration_commit_object",
        is_commit_object(root, registration),
        f"the recorded protocol-registration commit {registration!r} is not a real "
        "commit in this repository",
    ):
        return result()
    try:
        history_registration = m2b_report.protocol_commit_from_history(root)
        checks.append("evidence:registration_history_resolved")
    except Exception as exc:
        errors.append(f"evidence:registration_history_resolved: {exc}")
        return result()
    if not check(
        "evidence:registration_history",
        registration == history_registration,
        f"the recorded registration commit {registration!r} is not the commit that "
        f"actually froze the protocol per git history ({history_registration!r}) — "
        "a relabelled registration cannot verify",
    ):
        return result()
    try:
        train_validation = evaluation.evaluate_train_validation(dataset, protocol)
        results = evaluation.build_benchmark_results(
            dataset,
            protocol,
            train_validation,
            protocol_registration_commit_sha=registration,
            test_evaluation_id=None,
        )
        state["registration"] = registration
        state["train_validation"] = train_validation
        state["results"] = results
        checks.append("evidence:regenerate")
    except Exception as exc:
        errors.append(f"evidence:regenerate: {exc}")
        return result()
    if not check(
        "evidence:results_bytes",
        results.to_json_bytes() == (research / "train_validation_results.json").read_bytes(),
        "the committed train/validation results do not regenerate byte-for-byte",
    ):
        return result()
    try:
        rendered_report = m2b_report.render_report(root, results)
    except Exception as exc:
        errors.append(f"evidence:report_bytes: {exc}")
        return result()
    if not check(
        "evidence:report_bytes",
        rendered_report == (research / "train_validation_report.md").read_text(encoding="utf-8"),
        "the committed train/validation report does not regenerate byte-for-byte",
    ):
        return result()
    try:
        decision = build_research_decision_from_results(results)
        state["decision"] = decision
        checks.append("evidence:decision_rebuild")
    except Exception as exc:
        errors.append(f"evidence:decision_rebuild: {exc}")
        return result()
    if not check(
        "evidence:decision_bytes",
        decision.to_json_bytes() == (research / "validation_decision.json").read_bytes(),
        "the committed validation decision does not rebuild byte-for-byte",
    ):
        return result()
    if not check(
        "evidence:decision_markdown",
        render_research_decision(decision)
        == (research / "validation_decision.md").read_text(encoding="utf-8"),
        "the committed decision Markdown is not the rendering of the decision model",
    ):
        return result()

    # --- 13. Independent audit section. -------------------------------------
    audit = dossier.independent_audit
    if audit.status == AUDIT_NOT_PERFORMED:
        checks.append(f"audit:explicitly_not_performed ({audit.reason})")
    else:
        try:
            audit_file = root / REACQUISITION_AUDIT_RELPATH
            record = ReacquisitionAudit.from_json_bytes(audit_file.read_bytes())
            assert audit.audit_attempt_id is not None
            audit_dir = _attempt_dir(root, audit.audit_attempt_id)
            audit_receipt = load_acquisition_receipt(audit_dir / "acquisition_receipt.json")
            audit_bundle = raw_bundle_fingerprint(audit_receipt, audit_dir)
            for name, ok, detail in (
                (
                    "audit:record_hash",
                    sha256_file(audit_file) == audit.reacquisition_audit_sha256,
                    "reacquisition audit bytes differ from the dossier",
                ),
                (
                    "audit:status",
                    record.comparison_status == audit.status == AUDIT_CANONICAL_CONTENT_MATCH,
                    "a dossier only verifies with a canonical_content_match audit",
                ),
                (
                    "audit:attempt",
                    record.audit_attempt_id == audit.audit_attempt_id
                    and record.original_attempt_id == dossier.selected_attempt_id,
                    "audit attempt ids disagree",
                ),
                (
                    "audit:plan",
                    record.audit_request_plan_sha256
                    == audit.audit_request_plan_sha256
                    == dossier.acquisition_request_plan_sha256,
                    "the audit must fulfil the unchanged canonical plan",
                ),
                (
                    "audit:receipt_hash",
                    sha256_file(audit_dir / "acquisition_receipt.json")
                    == audit.audit_receipt_sha256
                    == record.audit_receipt_sha256,
                    "audit receipt bytes disagree",
                ),
                (
                    "audit:raw_bundle",
                    audit_bundle
                    == audit.audit_raw_bundle_fingerprint
                    == record.audit_raw_bundle_fingerprint,
                    "audit raw bundle fingerprint disagrees",
                ),
                (
                    "audit:original_chain",
                    record.original_receipt_sha256 == dossier.acquisition_receipt_sha256
                    and record.original_raw_bundle_fingerprint == dossier.raw_bundle_fingerprint
                    and record.original_content_fingerprint == dossier.dataset_content_fingerprint
                    and record.original_derived_csv_sha256 == dossier.derived_csv_sha256,
                    "the audit's recorded original chain differs from the dossier",
                ),
                (
                    "audit:content_match",
                    record.audit_content_fingerprint == dossier.dataset_content_fingerprint,
                    "the audit content fingerprint does not equal the canonical one",
                ),
            ):
                if not check(name, ok, detail):
                    return result()
            checks.append("audit:verified")
        except Exception as exc:
            errors.append(f"audit:verify: {exc}")
            return result()

    # --- 14. One version chain. ---------------------------------------------
    runtime = load_runtime_contract(research / "runtime_contract.json")
    versions = {
        "plan": plan.package_version,
        "receipt": receipt.package_version,
        "evidence": evidence.package_version,
        "manifest": dataset.manifest.package_version,
        "lock": lock.package_version,
        "runtime": runtime.package_version,
        "protocol": protocol.package_version,
        "results": results.package_version,
        "dossier": dossier.package_version,
        "running": __version__,
    }
    check(
        "version_chain",
        len(set(versions.values())) == 1,
        f"package versions disagree: {versions}",
    )
    return result()
